import sys
from pathlib import Path

# Allow importing the parent CycleGAN modules
sys.path.insert(0, str(Path(__file__).parent.parent))

import config as base

# ecgpcx-ray/ root (4 levels up from models/CycleGAN/mask/config.py)
_DATA_ROOT = Path(__file__).parent.parent.parent.parent / "data" / "processed"

# Inherit all base hyperparameters
DEVICE = base.DEVICE
IMAGE_SIZE = base.IMAGE_SIZE
BATCH_SIZE = base.BATCH_SIZE
NUM_WORKERS = base.NUM_WORKERS
EPOCHS = base.EPOCHS
LR = base.LR
LAMBDA_CYCLE = base.LAMBDA_CYCLE
LAMBDA_IDENTITY = base.LAMBDA_IDENTITY

# Mask-specific loss weights — outside-lung is penalized more to preserve background
LAMBDA_MASK_INSIDE = 1.0    # weight for inside-lung cycle/identity loss
LAMBDA_MASK_OUTSIDE = 3.0   # weight for outside-lung (background preservation)

# Image directories (resolved from base config via _DATA_ROOT)
TRAIN_HEALTHY_DIR   = base.TRAIN_HEALTHY_DIR
TRAIN_PNEUMONIA_DIR = base.TRAIN_PNEUMONIA_DIR
VAL_HEALTHY_DIR     = base.VAL_HEALTHY_DIR
VAL_PNEUMONIA_DIR   = base.VAL_PNEUMONIA_DIR

# Mask directories — generated by prepare_masks.py, same filenames as images
TRAIN_HEALTHY_MASKS_DIR   = str(_DATA_ROOT / "train" / "healthy_masks")
TRAIN_PNEUMONIA_MASKS_DIR = str(_DATA_ROOT / "train" / "pneumonia_masks")
VAL_HEALTHY_MASKS_DIR     = str(_DATA_ROOT / "val"   / "healthy_masks")
VAL_PNEUMONIA_MASKS_DIR   = str(_DATA_ROOT / "val"   / "pneumonia_masks")

# Output paths — separate from the no-mask version
CHECKPOINT_DIR = "mask/checkpoints"
