"""Single-image Point-E inference and visualization script.

This script loads a single RGB image, runs the Point-E pipeline with optional
fine-tuned weights, and visualizes the predicted point cloud using Open3D.
It is intended for quick manual inspection of a trained model on one sample.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np
import open3d as o3d
import torch
from PIL import Image

# Ensure src modules can be resolved when running this script directly.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.models.point_e_model import PotholePointE


def visualize_point_cloud(coords: np.ndarray) -> None:
    """Render a point cloud with Open3D."""
    point_cloud = o3d.geometry.PointCloud()
    point_cloud.points = o3d.utility.Vector3dVector(coords)
    o3d.visualization.draw_geometries([point_cloud])


def run_prediction(args) -> np.ndarray:
    """Load the image, run Point-E inference, and return predicted coordinates."""
    image_path = Path(args.image_path)
    if not image_path.exists():
        raise FileNotFoundError(f"Image not found at {image_path}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = PotholePointE(
        device=device,
        base_model_name=args.base_model,
        custom_base_weights_path=args.custom_weights,
        num_points_base=args.points_base,
        num_points_upsample=args.points_upsample,
        guidance_scale_base=args.guidance_base,
        guidance_scale_upsample=args.guidance_upsample,
        use_upsampler=args.use_upsample,
    )

    image = Image.open(image_path).convert("RGB")
    coords = model.predict(image, scale=args.scale)

    if args.output_path is not None:
        output_path = Path(args.output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        np.save(output_path, coords)
        print(f"Saved prediction to {output_path}")

    print(f"Predicted point cloud shape: {coords.shape}")
    visualize_point_cloud(coords)
    return coords


def main() -> None:
    """Parse CLI arguments and run a single-image inference pass."""
    parser = argparse.ArgumentParser(description="Single-image Point-E inference and visualization.")
    parser.add_argument("--image-path", type=str, required=True, help="Path to a single RGB image")
    parser.add_argument("--output-path", type=str, default=None, help="Optional .npy path to save predicted coords")
    parser.add_argument("--custom-weights", type=str, default=None, help="Path to fine-tuned base model weights")
    parser.add_argument("--base-model", type=str, default="base40M", help="Base Point-E model name")
    parser.add_argument("--points-base", type=int, default=1024, help="Points generated by the base model")
    parser.add_argument("--points-upsample", type=int, default=4096, help="Total points after upsampling")
    parser.add_argument("--guidance-base", type=float, default=3.0, help="Guidance scale for the base model")
    parser.add_argument("--guidance-upsample", type=float, default=3.0, help="Guidance scale for the upsampler")
    parser.add_argument("--use-upsample", action="store_true", help="Enable the upsampler stage (disabled by default)")
    parser.add_argument("--scale", type=float, default=1.0, help="Scale factor passed to Point-E output de-normalization")

    args = parser.parse_args()
    run_prediction(args)


if __name__ == "__main__":
    main()