"""Run final-test Point-E inference for a chosen checkpoint.

This script keeps the orchestration thin: it validates the checkpoint and test
set paths, delegates batch prediction to the existing Point-E batch pipeline,
and writes a reproducible run manifest into the dedicated final-test artifacts
folder.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import sys
from pathlib import Path

# Ensure src modules can be resolved when running this script directly.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.evaluation.final_test_eval import (
    FINAL_TEST_PREDICTIONS_DIR,
    FinalTestRunInfo,
    ensure_final_test_dirs,
    resolve_prepared_test_paths,
    write_run_info,
)
from src.models.predict_batch import process_batch


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser for final-test inference."""

    parser = argparse.ArgumentParser(description="Run final-test inference for a selected Point-E checkpoint.")
    parser.add_argument("--checkpoint", type=str, required=True, help="Path to the checkpoint to evaluate")
    parser.add_argument("--prepared_test_set", type=str, required=True, help="Path to the prepared test-set root")
    parser.add_argument("--images_dir", type=str, default=None, help="Optional override for the prepared test images directory")
    parser.add_argument("--metadata_path", type=str, default=None, help="Optional override for the prepared metadata.json path")
    parser.add_argument("--output_dir", type=str, default=str(FINAL_TEST_PREDICTIONS_DIR), help="Directory where prediction .npy files will be written")
    parser.add_argument("--base_model", type=str, default="base40M", help="Base Point-E model architecture name")
    parser.add_argument("--points_base", type=int, default=1024, help="Points generated by the base model")
    parser.add_argument("--points_upsample", type=int, default=4096, help="Total points after upsampling")
    parser.add_argument("--guidance_base", type=float, default=3.0, help="Guidance scale for the base model")
    parser.add_argument("--guidance_upsample", type=float, default=3.0, help="Guidance scale for the upsampler")
    return parser


def main() -> int:
    """Run Point-E inference over the prepared final-test set."""

    parser = build_parser()
    args = parser.parse_args()

    paths = ensure_final_test_dirs()

    checkpoint_path = Path(args.checkpoint)
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint not found at {checkpoint_path}")

    prepared_test_set = Path(args.prepared_test_set)
    prepared_paths = resolve_prepared_test_paths(prepared_test_set)
    if not prepared_paths.root.exists():
        raise FileNotFoundError(f"Prepared test set not found at {prepared_paths.root}")

    images_dir = Path(args.images_dir) if args.images_dir else prepared_paths.images_dir
    metadata_path = Path(args.metadata_path) if args.metadata_path else prepared_paths.metadata_path

    if not images_dir.exists():
        raise FileNotFoundError(f"Prepared test images directory not found at {images_dir}")
    if not metadata_path.exists():
        raise FileNotFoundError(f"Prepared metadata file not found at {metadata_path}")

    output_dir = Path(args.output_dir)
    existing_predictions = list(output_dir.glob("*.npy")) if output_dir.exists() else []
    if existing_predictions:
        raise FileExistsError(
            f"Final-test predictions already exist in {output_dir}. Remove them before rerunning inference."
        )

    inference_args = argparse.Namespace(
        images_dir=str(images_dir),
        metadata_path=str(metadata_path),
        output_dir=str(output_dir),
        custom_weights=str(checkpoint_path),
        base_model=args.base_model,
        points_base=args.points_base,
        points_upsample=args.points_upsample,
        guidance_base=args.guidance_base,
        guidance_upsample=args.guidance_upsample,
    )

    process_batch(inference_args)

    sample_count = len(list(output_dir.glob("*.npy")))
    if sample_count == 0:
        raise RuntimeError(f"No predictions were generated in {output_dir}; final-test inference did not produce outputs.")

    run_info = FinalTestRunInfo(
        checkpoint_path=str(checkpoint_path),
        prepared_test_set=str(prepared_paths.root),
        prepared_test_metadata=str(metadata_path),
        predictions_dir=str(output_dir),
        reports_dir=str(paths["reports_dir"]),
        evaluated_samples=sample_count,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )
    write_run_info(run_info, paths["run_info_path"])

    print(f"Final-test inference completed. Predictions: {output_dir.resolve()}")
    print(f"Run metadata written to: {paths['run_info_path'].resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())