"""
Point-E Baseline Inference Orchestrator.

This script acts as the batch processor for testing the Point-E model across
the entire pothole dataset. It utilizes the PotholePointE class for inference.
"""

import json
import argparse
from pathlib import Path
import numpy as np
import torch
from PIL import Image
from tqdm.auto import tqdm

# Import our pure Object-Oriented engine
from src.models.point_e_model import PotholePointE

# Define absolute paths dynamically relative to this script
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# --- Global Configuration Constants ---
DEFAULT_DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "point_e_ready"
DEFAULT_IMAGES_DIR = DEFAULT_DATA_PROCESSED_DIR / "images"
DEFAULT_METADATA_PATH = DEFAULT_DATA_PROCESSED_DIR / "metadata.json"

DEFAULT_OUTPUT_PREDICTIONS_DIR = PROJECT_ROOT / "data" / "interim" / "point_e_baseline_predictions"
DEFAULT_REPORTS_DIR = PROJECT_ROOT / "reports"
DEFAULT_REPORT_PATH = DEFAULT_REPORTS_DIR / "point_e_baseline_results.csv"

VALID_IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png"}

# Generation Magic Numbers Defaults
DEFAULT_POINTS_BASE = 1024
DEFAULT_POINTS_UPSAMPLE = 4096
DEFAULT_GUIDANCE_BASE = 3.0
DEFAULT_GUIDANCE_UPSAMPLE = 3.0

def process_batch(args):
    """Execution block for processing a full dataset of images."""
    images_dir = Path(args.images_dir)
    metadata_path = Path(args.metadata_path)
    output_predictions_dir = Path(args.output_dir)
    
    # Ensure output directories exist
    output_predictions_dir.mkdir(parents=True, exist_ok=True)
    
    print("--- Point-E Baseline/Custom Batch Inference Setup ---")
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # Load metadata
    print("Loading metadata...")
    if not metadata_path.exists():
        print(f"Error: Metadata file not found at {metadata_path}")
        return
        
    with open(metadata_path, 'r') as f:
        metadata = json.load(f)
    scales_dict = metadata.get("scales", {})

    # Initialize the pure inference class
    model = PotholePointE(
        device=device,
        base_model_name=args.base_model,
        custom_base_weights_path=args.custom_weights,
        num_points_base=args.points_base,
        num_points_upsample=args.points_upsample,
        guidance_scale_base=args.guidance_base,
        guidance_scale_upsample=args.guidance_upsample
    )

    # Iterate over images supporting multiple extensions
    image_paths = [p for p in images_dir.iterdir() if p.is_file() and p.suffix.lower() in VALID_IMAGE_EXTENSIONS]
    print(f"Found {len(image_paths)} valid images.")

    # Filter out already processed images (checkpointing logic)
    pending_image_paths = []
    for img_path in image_paths:
        expected_out_file = output_predictions_dir / f"{img_path.stem}.npy"
        if not expected_out_file.exists():
            pending_image_paths.append(img_path)

    if not pending_image_paths:
        print("All images have already been processed. Exiting.")
        return

    print(f"Starting batch processing for {len(pending_image_paths)} remaining images...")

    for img_path in tqdm(pending_image_paths, desc="Processing images"):
        stem = img_path.stem 
        scale = scales_dict.get(stem)
        
        if scale is None:
            print(f"Warning: No scale found in metadata for {stem}. Skipping.")
            continue
            
        try:
            # Load the image and predict statefully
            img = Image.open(img_path)
            coords = model.predict(img, scale)
            
            # Save to .npy
            out_file = output_predictions_dir / f"{stem}.npy"
            np.save(out_file, coords)
            
        except Exception as e:
            print(f"Error processing {stem}: {e}")

def main():
    parser = argparse.ArgumentParser(description="Batch Point-E inference for pothole 3D generation.")
    
    # Path Arguments
    parser.add_argument("--images_dir", type=str, default=str(DEFAULT_IMAGES_DIR), help="Directory containing input JPGs")
    parser.add_argument("--metadata_path", type=str, default=str(DEFAULT_METADATA_PATH), help="Path to metadata JSON")
    parser.add_argument("--output_dir", type=str, default=str(DEFAULT_OUTPUT_PREDICTIONS_DIR), help="Output NPY directory")
    
    # Model Weights Arguments
    parser.add_argument("--custom_weights", type=str, default=None, help="Path to local fine-tuned .pt weights")
    parser.add_argument("--base_model", type=str, default="base40M", help="Base model architecture name (e.g. base40M, base300M)")
    
    # Magic Numbers / Generation Constants
    parser.add_argument("--points_base", type=int, default=DEFAULT_POINTS_BASE, help="Points generated by base model")
    parser.add_argument("--points_upsample", type=int, default=DEFAULT_POINTS_UPSAMPLE, help="Target total points after upsampling")
    parser.add_argument("--guidance_base", type=float, default=DEFAULT_GUIDANCE_BASE, help="Guidance scale for base model")
    parser.add_argument("--guidance_upsample", type=float, default=DEFAULT_GUIDANCE_UPSAMPLE, help="Guidance scale for upsampler")

    args = parser.parse_args()
    process_batch(args)

if __name__ == "__main__":
    main()
