experiment_name: baseline_cnn

model:
  name: SimpleCNN
  dropout: 0.3

data:
  img_size: [224, 224]
  augmentation: false
  class_balancing: pos_weight  # weighted_random_sampler | pos_weight | none

training:
  batch_size: 64
  lr: 3.0e-4
  num_epochs: 100
  weight_decay: 1.0e-4
  early_stopping_patience: 10

seed: 42
